import Head from "next/head";
import LayoutStyle from "./layout.module.css";

export default function Layout({ children, signin }) {
  return (
    <div
      className={`${LayoutStyle.layout} ${signin ? LayoutStyle.signin : ""}`}
    >
      <Head>
        <title>Posts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
      <footer className={LayoutStyle.footer}>
        <h4>Welcome to my app</h4>
      </footer>
    </div>
  );
}
